# docker exec -it explorer-db /bin/bash /opt/createdb.sh
version: '3.5'

networks:
  akc-net:
    name: $NETWORK_NAME

services:
  explorer:
    image: akachain/devtool-explorer
    environment:
      - DATABASE_HOST=explorer-db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWD=Akachain
    ports:
      - "8080:8080"
    volumes:
      - ./artifacts/crypto-config/:/opt/explorer/crypto-config/
      - ./artifacts/config-explorer/:/opt/explorer/app/platform/fabric/config/
      - ./user/crypto-path/:/opt/explorer/crypto-path/
      - ./user/crypto-store/:/tmp/crypto-store/
    container_name: explorer
    # command: tail -f /opt/explorer/main.js
    networks:
      - akc-net